// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnDzkf-JULpVwPQ5J8iHHXf4mZkuR62Uc',
    appId: '1:880448137854:web:173f241ef1da43ec72c62f',
    messagingSenderId: '880448137854',
    projectId: 'carmanten-fd80f',
    authDomain: 'carmanten-fd80f.firebaseapp.com',
    storageBucket: 'carmanten-fd80f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2WiLNpkTteBZtSWGr46zM74xIvH2OAvg',
    appId: '1:880448137854:android:42e8749709ae030872c62f',
    messagingSenderId: '880448137854',
    projectId: 'carmanten-fd80f',
    storageBucket: 'carmanten-fd80f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0d3TuHROr_I_rXHz2VSoXiE-_Ng2bOTg',
    appId: '1:880448137854:ios:d621c1aae56411b972c62f',
    messagingSenderId: '880448137854',
    projectId: 'carmanten-fd80f',
    storageBucket: 'carmanten-fd80f.firebasestorage.app',
    iosBundleId: 'com.example.carmanten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0d3TuHROr_I_rXHz2VSoXiE-_Ng2bOTg',
    appId: '1:880448137854:ios:d621c1aae56411b972c62f',
    messagingSenderId: '880448137854',
    projectId: 'carmanten-fd80f',
    storageBucket: 'carmanten-fd80f.firebasestorage.app',
    iosBundleId: 'com.example.carmanten',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnDzkf-JULpVwPQ5J8iHHXf4mZkuR62Uc',
    appId: '1:880448137854:web:d9551c1e7cce2cb172c62f',
    messagingSenderId: '880448137854',
    projectId: 'carmanten-fd80f',
    authDomain: 'carmanten-fd80f.firebaseapp.com',
    storageBucket: 'carmanten-fd80f.firebasestorage.app',
  );
}
